 ttx -f -d output/ttx Sudo-Regular.ttf
 ttx -f -d output/ttx Sudo-Italic.ttf
 ttx -f -d output/ttx Sudo-Bold.ttf
 ttx -f -d output/ttx Sudo-BoldItalic.ttf
 ttx -f -d output/ttx Sudo-Light.ttf
 ttx -f -d output/ttx Sudo-LightItalic.ttf
 ttx -f -d output/ttx Sudo-Medium.ttf
 ttx -f -d output/ttx Sudo-MediumItalic.ttf
 ttx -f -d output/ttx Sudo-Thin.ttf
 ttx -f -d output/ttx Sudo-ThinItalic.ttf